# Generated by Django 6.0.4 on 2026-05-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('las_islas_es', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('image_name', models.CharField(blank=True, default='default.jpg', help_text='Enter file name (eg Cancun.jpg)', max_length=30)),
            ],
        ),
    ]
