# Generated by Django 6.0.4 on 2026-05-12 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('las_islas_es', '0002_cardtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinations', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('image_name', models.CharField(blank=True, default='default.jpg', help_text='Enter file name (eg Cancun).', max_length=100)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='las_islas_es.cardtext')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
            },
        ),
    ]
